ln -sf /usr/bin/asan_symbolize-11 /usr/local/bin/asan_symbolize
ln -sf /usr/bin/bugpoint-11 /usr/local/bin/bugpoint
ln -sf /usr/bin/c-index-test-11 /usr/local/bin/c-index-test
ln -sf /usr/bin/clang++-11 /usr/local/bin/clang++
ln -sf /usr/bin/clang-11 /usr/local/bin/clang
ln -sf /usr/bin/clang-apply-replacements-11 /usr/local/bin/clang-apply-replacements
ln -sf /usr/bin/clang-change-namespace-11 /usr/local/bin/clang-change-namespace
ln -sf /usr/bin/clang-check-11 /usr/local/bin/clang-check
ln -sf /usr/bin/clang-cl-11 /usr/local/bin/clang-cl
ln -sf /usr/bin/clang-cpp-11 /usr/local/bin/clang-cpp
ln -sf /usr/bin/clangd-11 /usr/local/bin/clangd
ln -sf /usr/bin/clang-doc-11 /usr/local/bin/clang-doc
ln -sf /usr/bin/clang-extdef-mapping-11 /usr/local/bin/clang-extdef-mapping
ln -sf /usr/bin/clang-format-11 /usr/local/bin/clang-format
ln -sf /usr/bin/clang-format-diff-11 /usr/local/bin/clang-format-diff
ln -sf /usr/bin/clang-include-fixer-11 /usr/local/bin/clang-include-fixer
ln -sf /usr/bin/clang-move-11 /usr/local/bin/clang-move
ln -sf /usr/bin/clang-offload-bundler-11 /usr/local/bin/clang-offload-bundler
ln -sf /usr/bin/clang-offload-wrapper-11 /usr/local/bin/clang-offload-wrapper
ln -sf /usr/bin/clang-query-11 /usr/local/bin/clang-query
ln -sf /usr/bin/clang-refactor-11 /usr/local/bin/clang-refactor
ln -sf /usr/bin/clang-rename-11 /usr/local/bin/clang-rename
ln -sf /usr/bin/clang-reorder-fields-11 /usr/local/bin/clang-reorder-fields
ln -sf /usr/bin/clang-scan-deps-11 /usr/local/bin/clang-scan-deps
ln -sf /usr/bin/clang-tidy-11 /usr/local/bin/clang-tidy
ln -sf /usr/bin/count-11 /usr/local/bin/count
ln -sf /usr/bin/diagtool-11 /usr/local/bin/diagtool
ln -sf /usr/bin/dsymutil-11 /usr/local/bin/dsymutil
ln -sf /usr/bin/FileCheck-11 /usr/local/bin/FileCheck
ln -sf /usr/bin/find-all-symbols-11 /usr/local/bin/find-all-symbols
ln -sf /usr/bin/git-clang-format-11 /usr/local/bin/git-clang-format
ln -sf /usr/bin/hmaptool-11 /usr/local/bin/hmaptool
ln -sf /usr/bin/hwasan_symbolize-11 /usr/local/bin/hwasan_symbolize
ln -sf /usr/bin/llc-11 /usr/local/bin/llc
ln -sf /usr/bin/lli-11 /usr/local/bin/lli
ln -sf /usr/bin/lli-child-target-11 /usr/local/bin/lli-child-target
ln -sf /usr/bin/llvm-addr2line-11 /usr/local/bin/llvm-addr2line
ln -sf /usr/bin/llvm-ar-11 /usr/local/bin/llvm-ar
ln -sf /usr/bin/llvm-as-11 /usr/local/bin/llvm-as
ln -sf /usr/bin/llvm-bcanalyzer-11 /usr/local/bin/llvm-bcanalyzer
ln -sf /usr/bin/llvm-cat-11 /usr/local/bin/llvm-cat
ln -sf /usr/bin/llvm-cfi-verify-11 /usr/local/bin/llvm-cfi-verify
ln -sf /usr/bin/llvm-config-11 /usr/local/bin/llvm-config
ln -sf /usr/bin/llvm-cov-11 /usr/local/bin/llvm-cov
ln -sf /usr/bin/llvm-c-test-11 /usr/local/bin/llvm-c-test
ln -sf /usr/bin/llvm-cvtres-11 /usr/local/bin/llvm-cvtres
ln -sf /usr/bin/llvm-cxxdump-11 /usr/local/bin/llvm-cxxdump
ln -sf /usr/bin/llvm-cxxfilt-11 /usr/local/bin/llvm-cxxfilt
ln -sf /usr/bin/llvm-cxxmap-11 /usr/local/bin/llvm-cxxmap
ln -sf /usr/bin/llvm-diff-11 /usr/local/bin/llvm-diff
ln -sf /usr/bin/llvm-dis-11 /usr/local/bin/llvm-dis
ln -sf /usr/bin/llvm-dlltool-11 /usr/local/bin/llvm-dlltool
ln -sf /usr/bin/llvm-dwarfdump-11 /usr/local/bin/llvm-dwarfdump
ln -sf /usr/bin/llvm-dwp-11 /usr/local/bin/llvm-dwp
ln -sf /usr/bin/llvm-elfabi-11 /usr/local/bin/llvm-elfabi
ln -sf /usr/bin/llvm-exegesis-11 /usr/local/bin/llvm-exegesis
ln -sf /usr/bin/llvm-extract-11 /usr/local/bin/llvm-extract
ln -sf /usr/bin/llvm-gsymutil-11 /usr/local/bin/llvm-gsymutil
ln -sf /usr/bin/llvm-ifs-11 /usr/local/bin/llvm-ifs
ln -sf /usr/bin/llvm-install-name-tool-11 /usr/local/bin/llvm-install-name-tool
ln -sf /usr/bin/llvm-jitlink-11 /usr/local/bin/llvm-jitlink
ln -sf /usr/bin/llvm-lib-11 /usr/local/bin/llvm-lib
ln -sf /usr/bin/llvm-link-11 /usr/local/bin/llvm-link
ln -sf /usr/bin/llvm-lipo-11 /usr/local/bin/llvm-lipo
ln -sf /usr/bin/llvm-lto-11 /usr/local/bin/llvm-lto
ln -sf /usr/bin/llvm-lto2-11 /usr/local/bin/llvm-lto2
ln -sf /usr/bin/llvm-mc-11 /usr/local/bin/llvm-mc
ln -sf /usr/bin/llvm-mca-11 /usr/local/bin/llvm-mca
ln -sf /usr/bin/llvm-ml-11 /usr/local/bin/llvm-ml
ln -sf /usr/bin/llvm-modextract-11 /usr/local/bin/llvm-modextract
ln -sf /usr/bin/llvm-mt-11 /usr/local/bin/llvm-mt
ln -sf /usr/bin/llvm-nm-11 /usr/local/bin/llvm-nm
ln -sf /usr/bin/llvm-objcopy-11 /usr/local/bin/llvm-objcopy
ln -sf /usr/bin/llvm-objdump-11 /usr/local/bin/llvm-objdump
ln -sf /usr/bin/llvm-opt-report-11 /usr/local/bin/llvm-opt-report
ln -sf /usr/bin/llvm-pdbutil-11 /usr/local/bin/llvm-pdbutil
ln -sf /usr/bin/llvm-PerfectShuffle-11 /usr/local/bin/llvm-PerfectShuffle
ln -sf /usr/bin/llvm-profdata-11 /usr/local/bin/llvm-profdata
ln -sf /usr/bin/llvm-ranlib-11 /usr/local/bin/llvm-ranlib
ln -sf /usr/bin/llvm-rc-11 /usr/local/bin/llvm-rc
ln -sf /usr/bin/llvm-readelf-11 /usr/local/bin/llvm-readelf
ln -sf /usr/bin/llvm-readobj-11 /usr/local/bin/llvm-readobj
ln -sf /usr/bin/llvm-reduce-11 /usr/local/bin/llvm-reduce
ln -sf /usr/bin/llvm-rtdyld-11 /usr/local/bin/llvm-rtdyld
ln -sf /usr/bin/llvm-size-11 /usr/local/bin/llvm-size
ln -sf /usr/bin/llvm-split-11 /usr/local/bin/llvm-split
ln -sf /usr/bin/llvm-stress-11 /usr/local/bin/llvm-stress
ln -sf /usr/bin/llvm-strings-11 /usr/local/bin/llvm-strings
ln -sf /usr/bin/llvm-strip-11 /usr/local/bin/llvm-strip
ln -sf /usr/bin/llvm-symbolizer-11 /usr/local/bin/llvm-symbolizer
ln -sf /usr/bin/llvm-tblgen-11 /usr/local/bin/llvm-tblgen
ln -sf /usr/bin/llvm-undname-11 /usr/local/bin/llvm-undname
ln -sf /usr/bin/llvm-xray-11 /usr/local/bin/llvm-xray
ln -sf /usr/bin/modularize-11 /usr/local/bin/modularize
ln -sf /usr/bin/not-11 /usr/local/bin/not
ln -sf /usr/bin/obj2yaml-11 /usr/local/bin/obj2yaml
ln -sf /usr/bin/opt-11 /usr/local/bin/opt
ln -sf /usr/bin/pp-trace-11 /usr/local/bin/pp-trace
ln -sf /usr/bin/run-clang-tidy-11 /usr/local/bin/run-clang-tidy
ln -sf /usr/bin/sancov-11 /usr/local/bin/sancov
ln -sf /usr/bin/sanstats-11 /usr/local/bin/sanstats
ln -sf /usr/bin/scan-build-11 /usr/local/bin/scan-build
ln -sf /usr/bin/scan-build-py-11 /usr/local/bin/scan-build-py
ln -sf /usr/bin/scan-view-11 /usr/local/bin/scan-view
ln -sf /usr/bin/verify-uselistorder-11 /usr/local/bin/verify-uselistorder
ln -sf /usr/bin/yaml2obj-11 /usr/local/bin/yaml2obj
ln -sf /usr/bin/yaml-bench-11 /usr/local/bin/yaml-bench
