#!/bin/bash
# set environmental variable for intel-compiler
export ONEAPI_ROOT=/opt/intel/oneapi
export PATH=/opt/intel/oneapi/vtune/latest/bin64:/opt/intel/oneapi/vpl/latest/bin:/opt/intel/oneapi/mpi/latest/libfabric/bin:/opt/intel/oneapi/mpi/latest/bin:/opt/intel/oneapi/mkl/latest/bin/intel64:/opt/intel/oneapi/itac/latest/bin:/opt/intel/oneapi/inspector/latest/bin64:/opt/intel/oneapi/dpcpp-ct/latest/bin:/opt/intel/oneapi/dev-utilities/latest/bin:/opt/intel/oneapi/debugger/latest/gdb/intel64/bin:/opt/intel/oneapi/compiler/latest/linux/lib/oclfpga/llvm/aocl-bin:/opt/intel/oneapi/compiler/latest/linux/lib/oclfpga/bin:/opt/intel/oneapi/compiler/latest/linux/bin/intel64:/opt/intel/oneapi/clck/latest/bin/intel64:/opt/intel/oneapi/advisor/latest/bin64:${PATH}
export PKG_CONFIG_PATH=/opt/intel/oneapi/vtune/latest/include/pkgconfig/lib64:/opt/intel/oneapi/vpl/latest/lib/pkgconfig:/opt/intel/oneapi/mkl/latest/tools/pkgconfig:/opt/intel/oneapi/inspector/latest/include/pkgconfig/lib64:/opt/intel/oneapi/advisor/latest/include/pkgconfig/lib64:${PKG_CONFIG_PATH}
export ADVISOR_2023_DIR=/opt/intel/oneapi/advisor/latest
export PYTHONPATH=/opt/intel/oneapi/advisor/latest/pythonapi:${PYTHONPATH}
export APM=/opt/intel/oneapi/advisor/latest/perfmodels
export CCL_ROOT=/opt/intel/oneapi/ccl/latest
export CCL_CONFIGURATION=cpu_gpu_dpcpp
export CPATH=/opt/intel/oneapi/vpl/latest/include:/opt/intel/oneapi/tbb/latest/env/../include:/opt/intel/oneapi/mpi/latest/include:/opt/intel/oneapi/mkl/latest/include:/opt/intel/oneapi/ipp/latest/include:/opt/intel/oneapi/ippcp/latest/include:/opt/intel/oneapi/ipp/latest/include:/opt/intel/oneapi/dpl/latest/linux/include:/opt/intel/oneapi/dpcpp-ct/latest/include:/opt/intel/oneapi/dnnl/latest/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/dev-utilities/latest/include:/opt/intel/oneapi/dal/latest/include:/opt/intel/oneapi/compiler/latest/linux/include:/opt/intel/oneapi/ccl/latest/include/cpu_gpu_dpcpp:${CPATH}
export LIBRARY_PATH=/opt/intel/oneapi/vpl/latest/lib:/opt/intel/oneapi/tbb/latest/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/latest/libfabric/lib:/opt/intel/oneapi/mpi/latest/lib/release:/opt/intel/oneapi/mpi/latest/lib:/opt/intel/oneapi/mkl/latest/lib/intel64:/opt/intel/oneapi/ipp/latest/lib/intel64:/opt/intel/oneapi/ippcp/latest/lib/intel64:/opt/intel/oneapi/ipp/latest/lib/intel64:/opt/intel/oneapi/dnnl/latest/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/dal/latest/lib/intel64:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/latest/linux/lib:/opt/intel/oneapi/clck/latest/lib/intel64:/opt/intel/oneapi/ccl/latest/lib/cpu_gpu_dpcpp:${LIBRARAY_PATH}
export LD_LIBRARY_PATH=/opt/intel/oneapi/vpl/latest/lib:/opt/intel/oneapi/tbb/latest/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/latest/libfabric/lib:/opt/intel/oneapi/mpi/latest/lib/release:/opt/intel/oneapi/mpi/latest/lib:/opt/intel/oneapi/mkl/latest/lib/intel64:/opt/intel/oneapi/itac/latest/slib:/opt/intel/oneapi/ipp/latest/lib/intel64:/opt/intel/oneapi/ippcp/latest/lib/intel64:/opt/intel/oneapi/ipp/latest/lib/intel64:/opt/intel/oneapi/dnnl/latest/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/debugger/latest/gdb/intel64/lib:/opt/intel/oneapi/debugger/latest/libipt/intel64/lib:/opt/intel/oneapi/debugger/latest/dep/lib:/opt/intel/oneapi/dal/latest/lib/intel64:/opt/intel/oneapi/compiler/latest/linux/lib:/opt/intel/oneapi/compiler/latest/linux/lib/x64:/opt/intel/oneapi/compiler/latest/linux/lib/emu:/opt/intel/oneapi/compiler/latest/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/latest/linux/lib/oclfpga/linux64/lib:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/ccl/latest/lib/cpu_gpu_dpcpp:${LD_LIBRARY_PATH}
export CLCK_ROOT=/opt/intel/oneapi/clck/latest
export CPLUS_INCLUDE_PATH=/opt/intel/oneapi/clck/latest/include
export INTEL_LICENSE_FILE=/opt/intel/licenses:/opt/intel/oneapi/clck/latest/licensing:/opt/intel/licenses
export MANPATH=/opt/intel/oneapi/mpi/latest/man:/opt/intel/oneapi/itac/latest/man:/opt/intel/oneapi/debugger/latest/documentation/man:/opt/intel/oneapi/compiler/latest/documentation/en/man/common:/opt/intel/oneapi/clck/latest/man:${MANPATH}
export CMPLR_ROOT=/opt/intel/oneapi/compiler/latest
export FPGA_VARS_DIR=/opt/intel/oneapi/compiler/latest/linux/lib/oclfpga
export FPGA_VARS_ARGS=
export OCL_ICD_FILENAMES=libintelocl_emu.so:libalteracl.so:/opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
export ACL_BOARD_VENDOR_PATH=/opt/Intel/OpenCLFPGA/oneAPI/Boards
export INTELFPGAOCLSDKROOT=/opt/intel/oneapi/compiler/latest/linux/lib/oclfpga
export DAL_MAJOR_BINARY=1
export DAL_MINOR_BINARY=1
export DALROOT=/opt/intel/oneapi/dal/latest
export DAALROOT=/opt/intel/oneapi/dal/latest
export CLASSPATH=/opt/intel/oneapi/mpi/latest/lib/mpi.jar:/opt/intel/oneapi/dal/latest/lib/onedal.jar
export CMAKE_PREFIX_PATH=/opt/intel/oneapi/vpl/latest:/opt/intel/oneapi/tbb/latest/env/..:/opt/intel/oneapi/dal/latest
export INTEL_PYTHONHOME=/opt/intel/oneapi/debugger/latest/dep
export INFOPATH=/opt/intel/oneapi/debugger/latest/gdb/intel64/lib
export DNNLROOT=/opt/intel/oneapi/dnnl/latest/cpu_dpcpp_gpu_dpcpp
export DPCT_BUNDLE_ROOT=/opt/intel/oneapi/dpcpp-ct/latest
export DPL_ROOT=/opt/intel/oneapi/dpl/latest
export INSPECTOR_2023_DIR=/opt/intel/oneapi/inspector/latest
# export CONDA_EXE=/opt/intel/oneapi/intelpython/latest/bin/conda
export _CE_M=
# export _CE_CONDA=
# export CONDA_PYTHON_EXE=/opt/intel/oneapi/intelpython/latest/bin/python
# export CONDA_SHLVL=1
# export CONDA_PREFIX=/opt/intel/oneapi/intelpython/latest
# export CONDA_DEFAULT_ENV=intelpython-python3.7
# export CONDA_PROMPT_MODIFIER=(intelpython-python3.7)
export IPPROOT=/opt/intel/oneapi/ipp/latest
export IPP_TARGET_ARCH=intel64
export IPPCRYPTOROOT=/opt/intel/oneapi/ippcp/latest
export IPPCP_TARGET_ARCH=intel64
export VT_ROOT=/opt/intel/oneapi/itac/latest
export VT_MPI=impi4
export VT_LIB_DIR=/opt/intel/oneapi/itac/latest/lib
export VT_SLIB_DIR=/opt/intel/oneapi/itac/latest/slib
export VT_ADD_LIBS="-ldwarf -lelf -lvtunwind -lm -lpthread"
export MKLROOT=/opt/intel/oneapi/mkl/latest
export NLSPATH=/opt/intel/oneapi/mkl/latest/lib/intel64/locale/%l_%t/%N
export I_MPI_ROOT=/opt/intel/oneapi/mpi/latest
export FI_PROVIDER_PATH=/opt/intel/oneapi/mpi/latest/libfabric/lib/prov:/usr/lib64/libfabric
export TBBROOT=/opt/intel/oneapi/tbb/latest/env/..
export VTUNE_PROFILER_2023_DIR=/opt/intel/oneapi/vtune/latest
