name: build_image

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 1 1/16 * *'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Set up docker tag
        run: |
          echo "IMAGE_TAG=machsix/ubuntu-impi:${{ steps.getversion.outputs.version }}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${{ steps.getversion.outputs.version }}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            VERSION=${{ env.IMAGE_VERSION }}
      - name: Export rootfs
        run: |
          docker export $(docker create ${IMAGE_TAG}) | gzip > ubuntu-impi-${IMAGE_VERSION}.tar.gz
          md5sum  ubuntu-impi-${IMAGE_VERSION}.tar.gz >  ubuntu-impi-${IMAGE_VERSION}.md5
      - name: Upload rootfs
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-impi-${{ env.IMAGE_VERSION }}.tar.gz
          path: ubuntu-impi-${{ env.IMAGE_VERSION }}.tar.gz
          if-no-files-found: error
      - name: Upload rootfs
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-impi-${{ env.IMAGE_VERSION }}.md5
          path: ubuntu-impi-${{ env.IMAGE_VERSION }}.md5
          if-no-files-found: error
